### ISSUE TITLE
Error cannot install google search console bulk url removal

### ISSUE THREAD

**Issue by phongdang19081991** [noitcudni/google-search-console-bulk-url-removal#127]
I downloaded Error cannot install **google search console bulk url removal** to delete self-generated Urls due to virus-infected websites. But when installing on **google extension**, it gives an error "**Manifest file is missing or unreadable. Manifest file cannot be loaded."**

Utility download link: [https://github.com/noitcudni/google-search-console-bulk-url-removal](https://github.com/noitcudni/google-search-console-bulk-url-removal)

Hope the developer helps

#123 url removal
#google search console bulk url removal

**Comment by noitcudni** [comment]
You'll have to purchase a license nowadays. Sorry.
